export const FORM_CREATE_REQUEST = 'FORM_CREATE_REQUEST'
export const FORM_CREATE_SUCCESS = 'FORM_CREATE_SUCCESS'
export const FORM_CREATE_FAIL = 'FORM_CREATE_FAIL'
export const FORM_CREATE_RESET = 'FORM_CREATE_RESET'