export const FORM_SUBMIT_REQUEST = 'FORM_SUBMIT_REQUEST'
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS'
export const FORM_SUBMIT_FAIL = 'FORM_SUBMIT_FAIL'
export const FORM_SUBMIT_RESET = 'FORM_SUBMIT_RESET'